### ISSUE TITLE
Alternating row color with selection mixin not showing selection for odd rows

### ISSUE THREAD

**Issue by schallm** [SitePen/dgrid#1252]
I am trying to get alternating row colors working with the selection extension. 

Here is an example: http://plnkr.co/edit/Bb30hFxBVHhJIBMyICqs?p=info

I found a [link here](https://www.sitepen.com/blog/2012/05/03/css-styling-of-dgrid/) suggesting the way to do this is with a .dgrid-row-odd:

```css
.dgrid-row-odd {
    background: #F2F5F9;
}
```

However if you are using a skin (i.e. claro) the coloring does not have enough specificity due to a rule in the [claro.css](https://github.com/SitePen/dgrid/blob/v1.0.0/css/skins/claro.css#L29) file:

```css
.claro .dgrid-row {
    background: #fff url("images/row_back.png") repeat-x;
    ... 
}
```

This can be resolve by adding your skin name to the rule above:

```css
.claro .dgrid-row-odd {
    background: #F2F5F9;
}
```

This however causes issues if you are using the selection mixin.  The rule for selection background color is defined in the [claro.css](https://github.com/SitePen/dgrid/blob/v1.0.0/css/skins/claro.css#L45) at the same specificity of the the alternating row color.  

```css
.claro .dgrid-selected {
  background-color: #cee6fa;
}
```

Since the alternating row color is defined later in the document in site specific code, it wins causing selected odd rows that are not being hovered to not show as selected. 

A potential fix is to add !important to the selected rules in the claro.styl file.

```css
$dgrid-selected-background-color ?= #cee6fa !important;
$dgrid-selected-hover-background-color ?= #9bc6f2 !important;
```

**Comment by kfranqueiro** [comment]
`!important` would almost certainly cause headaches elsewhere when customizing.

In your actual application, are you trying to override this with CSS or Stylus?  I can see where this could be troublesome with CSS (at least, without defining your own `selected` style as well), but with Stylus it should be super straightforward to override in your own skin:

```stylus
$dgrid-body-row-odd-background ?= #f7f7f7;
@import('path/to/dgrid/css/skins/claro');
```

**Comment by schallm** [comment]
I'm trying to override in CSS as the rest of our project doesn't use Stylus.  I can fix the issue since we have a custom skin, but it would be nice to not require other developers to create a skin just to make this common scenario work.

I know `!important` is usually a bad thing especially for libraries ([Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception)).

How about upping the specificity for the rule within the claro.css (potentially other skins as well)?  Any additional selector will make this work.

```css
.claro .dgrid .dgrid-selected {
  background-color: #cee6fa;
}
```

This gets rid of the important and allows developers to add the following rule without having to have their own skin.

```css
.claro .dgrid-row-odd {
    background: #F2F5F9;
}
```
